# Set theme
theme: alembic-jekyll-theme

# Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Lazbaj # jekyll-seo-tag > Owners twitter username
author: Laz # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Lazzaro Baj # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Lazbaj
    - https://www.facebook.com/lazbaj
    - https://github.com/Lazbaj

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Berlin # Timezone for blog posts and alike

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Qualche Pezzetto di me"
    feature_text: |
      Benvenuto tra questi appunti sparsi
    feature_image: "/assets/img/blog_header_apple_devices.jpg"

# Jekyll collections settings (front matter defaults)
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: "assets/img"
    values:
      image: true

# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: it-IT # Set the site language
title: 'Pieces of Laz'
logo: "https://www.gravatar.com/avatar/f99b82794a0bdf10fb121a102ccd34d5?s=52" # Site logo, also used in jekyll-seo-tag
description: 'Pezzetti di me: idee, progetti, pensieri su tecnologia, sport e fotografia' # Site description and default description, also used in jekyll-seo-tag
url: 'https://lazzarobaj.com' # Site url, also used in jekyll-seo-tag
baseurl: ''
repo: "https://github.com/Lazbaj/lazzarobaj-website"
email: "laz@lazzarobaj.com"
repository: "Lazbaj/lazzarobaj-website" # Name of repository, for use with Staticman
staticman:
  branch: "master" # Staticman comments (see staticman.yml for configuration)
avatarurl: "https://www.gravatar.com/avatar/f99b82794a0bdf10fb121a102ccd34d5" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
google_analytics: 'UA-301116-4'
service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  Categories: /categorie/
  Search: /cerca/

navigation_footer:
  Back to top: "#top"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # LinkedIn: https://www.linkedin.com/in/lazbaj
  Twitter: https://twitter.com/Lazbaj
  GitHub: https://github.com/Lazbaj
  Instagram: https://www.instagram.com/lazbaj/
  link: http://laz-giulia.it
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#a0a0a0"
  facebook: "#a0a0a0"
  tumblr: "#a0a0a0"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
